package presentacion;

public enum Events {
    MOSTRAR_PANEL,

    // Marca
    MOSTRAR_ALTA_MARCA, ALTA_MARCA,
    MOSTRAR_BAJA_MARCA, BAJA_MARCA,
    MOSTRAR_ACTUALIZAR_MARCA, ACTUALIZAR_MARCA,
    MOSTRAR_MOSTRAR_MARCA,
    MOSTRAR_UNO_ID_MARCA, MOSTRAR_UNO_NOMBRE_MARCA, MOSTRAR_TODO_MARCA,

    // Cliente
    MOSTRAR_ALTA_CLIENTE, ALTA_CLIENTE,
    MOSTRAR_BAJA_CLIENTE, BAJA_CLIENTE,
    MOSTRAR_ACTUALIZAR_CLIENTE, ACTUALIZAR_CLIENTE,
    MOSTRAR_MOSTRAR_CLIENTE,
    MOSTRAR_UNO_ID_CLIENTE, MOSTRAR_UNO_NIF_CLIENTE, MOSTRAR_TODO_CLIENTE,

    // Producto
    MOSTRAR_ALTA_PRODUCTO, ALTA_PRODUCTO,
    MOSTRAR_BAJA_PRODUCTO, BAJA_PRODUCTO,
    MOSTRAR_ACTUALIZAR_PRODUCTO, ACTUALIZAR_PRODUCTO,
    MOSTRAR_MOSTRAR_PRODUCTO,
    MOSTRAR_UNO_ID_PRODUCTO, MOSTRAR_TODO_MARCA_PRODUCTO, MOSTRAR_TODO_PRODUCTO,

    // Empleado / Trabajador
    MOSTRAR_ALTA_EMPLEADO, ALTA_EMPLEADO,
    MOSTRAR_BAJA_EMPLEADO, BAJA_EMPLEADO,
    MOSTRAR_ACTUALIZAR_EMPLEADO, ACTUALIZAR_EMPLEADO,
    MOSTRAR_MOSTRAR_EMPLEADO,
    MOSTRAR_UNO_ID_EMPLEADO, MOSTRAR_UNO_NIF_EMPLEADO, MOSTRAR_TODO_EMPLEADO,

    // Venta
    MOSTRAR_ABRIR_VENTA, CERRAR_VENTA,
    MOSTRAR_DEVOLUCION_VENTA, DEVOLUCION_VENTA,
    MOSTRAR_ACTUALIZAR_VENTA, ACTUALIZAR_VENTA,
    MOSTRAR_MOSTRAR_VENTA,
    MOSTRAR_UNO_ID_VENTA, MOSTRAR_VENTA_ID_CLIENTE, MOSTRAR_VENTA_ID_EMPLEADO,
    MOSTRAR_VENTA_FECHA, MOSTRAR_TODO_VENTA
}
