package presentacion;

public enum GUIEvents {
    ALTA_MARCA_OK, ALTA_MARCA_KO,
    BAJA_MARCA_OK, BAJA_MARCA_KO,
    ACTUALIZAR_MARCA_OK, ACTUALIZAR_MARCA_KO,
    MOSTRAR_MARCA_OK, MOSTRAR_MARCA_KO,

    ALTA_CLIENTE_OK, ALTA_CLIENTE_KO,
    BAJA_CLIENTE_OK, BAJA_CLIENTE_KO,
    ACTUALIZAR_CLIENTE_OK, ACTUALIZAR_CLIENTE_KO,
    MOSTRAR_CLIENTE_OK, MOSTRAR_CLIENTE_KO,

    ALTA_PRODUCTO_OK, ALTA_PRODUCTO_KO,
    BAJA_PRODUCTO_OK, BAJA_PRODUCTO_KO,
    ACTUALIZAR_PRODUCTO_OK, ACTUALIZAR_PRODUCTO_KO,
    MOSTRAR_PRODUCTO_OK, MOSTRAR_PRODUCTO_KO,

    ALTA_EMPLEADO_OK, ALTA_EMPLEADO_KO,
    BAJA_EMPLEADO_OK, BAJA_EMPLEADO_KO,
    ACTUALIZAR_EMPLEADO_OK, ACTUALIZAR_EMPLEADO_KO,
    MOSTRAR_EMPLEADO_OK, MOSTRAR_EMPLEADO_KO,

    ABRIR_VENTA_OK, ABRIR_VENTA_KO,
    CERRAR_VENTA_OK, CERRAR_VENTA_KO,
    DEVOLUCION_VENTA_OK, DEVOLUCION_VENTA_KO,
    ACTUALIZAR_VENTA_OK, ACTUALIZAR_VENTA_KO,
    MOSTRAR_VENTA_OK, MOSTRAR_VENTA_KO
}
